---
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'
  name: name
  namespace: namespace
type: Opaque

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'
    bmac.agent-install.openshift.io/hostname: 
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: 
    cluster-name: 
  name: name
  namespace: namespace
spec:
  automatedCleaningMode: disabled
  bmc:
    address: 
    credentialsName: 
    disableCertificateVerification: true
  bootMACAddress: 
  online: true

