---
apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'
  name: pull-secret
  namespace: namespace
type: kubernetes.io/dockerconfigjson

