---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-bmh.yaml
  - 02-pull-secret.yaml
  - 03-agentclusterinstall.yaml
  - 04-clusterdeployment.yaml
  - 05-klusterletaddonconfig.yaml
  - 06-managedcluster.yaml
  - 07-infraenv.yaml
