---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'  
  labels:
    name: sno2
    cluster-name: sno2
    base-domain: example.com
    day2-setup: true
  name: name

