---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  annotations:
    apps.open-cluster-management.io/do-not-delete: 'true'  
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: sno2
    networkType: dhcp
  name: name
  namespace: namespace
spec:
  clusterRef:
    name: sno2
    namespace: sno2
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: sno2
  sshAuthorizedKey: <sshPublicKey>
